version: 2

sources:
  - name: staging
    schema: heymax_staging
    tables:
      - name: raw_events
        description: "Raw user event data uploaded from GCS"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: event_time
        columns:
          - name: user_id
            description: "Unique ID for each user"
          - name: event_time
            description: "Timestamp of the user event"
          - name: event_type
            description: "Action performed by the user"
